[deploy]
bucket = 'llm-cfn-artifacts'
region = 'eu-west-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddur.es'
EnvBackendUrl = 'https://api.cruddur.es'
DDBMessageTable = 'CrdDdb-DynamoDBTable-G12N0ET4TBR0'