FROM 632758144135.dkr.ecr.eu-west-1.amazonaws.com/cruddur-python:3.10-slim-buster
#test with gitpod
#FROM python:3.10-slim-buster

#For debugging, don't leave in prod
#RUN apt-get update -y
#RUN apt-get install iputils-ping -y

WORKDIR /backend-flask

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE ${PORT}

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567", "--no-debug", "--no-debugger", "--no-reload"]
#RUN chmod +x start-flask.sh
#ENTRYPOINT ["./start-flask.sh"]